# Generated by Django 6.1.1 on 2026-09-11 16:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('business_name', models.CharField(max_length=255)),
                ('gstin', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(default='Kerala', max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OfficerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer_name', models.CharField(max_length=255)),
                ('designation', models.CharField(default='Senior Legal Metrology Officer', max_length=255)),
                ('badge_number', models.CharField(max_length=50, unique=True)),
                ('jurisdiction_zone', models.CharField(max_length=150)),
                ('district', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='officer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('applicant_name', models.CharField(max_length=255)),
                ('business_name', models.CharField(max_length=255)),
                ('gstin', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('premises_address', models.TextField()),
                ('district', models.CharField(max_length=100)),
                ('instrument_category', models.CharField(max_length=150)),
                ('instrument_type', models.CharField(max_length=255)),
                ('accuracy_class', models.CharField(max_length=100)),
                ('capacity', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=255)),
                ('model_number', models.CharField(max_length=150)),
                ('serial_number', models.CharField(db_index=True, max_length=150)),
                ('year_of_manufacture', models.IntegerField(default=2025)),
                ('verification_nature', models.CharField(default='Re-verification / Periodic Renewal', max_length=100)),
                ('inspection_venue', models.CharField(default='Trader Premises (On-site)', max_length=255)),
                ('status', models.CharField(choices=[('Application Submitted', 'Application Submitted'), ('Under Review', 'Under Review'), ('Returned for Correction', 'Returned for Correction'), ('Verification Scheduled', 'Verification Scheduled'), ('Inspection in Progress', 'Inspection in Progress'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Certificate Generated', 'Certificate Generated')], db_index=True, default='Application Submitted', max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('return_reason', models.TextField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('applicant_correction_notes', models.TextField(blank=True, null=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('scheduled_slot', models.CharField(blank=True, max_length=100, null=True)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('statutory_fee', models.DecimalField(decimal_places=2, default=850.0, max_digits=10)),
                ('fee_status', models.CharField(default='PAID_ONLINE', max_length=50)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='api.applicantprofile')),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.officerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField(default=django.utils.timezone.now)),
                ('standards_used', models.CharField(max_length=255)),
                ('mpe_tolerance', models.CharField(max_length=100)),
                ('max_observed_error', models.CharField(max_length=50)),
                ('seal_number', models.CharField(max_length=100, unique=True)),
                ('verdict', models.CharField(default='PASSED', max_length=20)),
                ('remarks', models.TextField()),
                ('raw_readings_json', models.JSONField(default=list)),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.officerprofile')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_record', to='api.verificationapplication')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('applicant_name', models.CharField(max_length=255)),
                ('business_name', models.CharField(max_length=255)),
                ('gstin', models.CharField(max_length=20)),
                ('premises_address', models.TextField()),
                ('instrument_type', models.CharField(max_length=255)),
                ('instrument_class', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=255)),
                ('model_number', models.CharField(max_length=150)),
                ('serial_number', models.CharField(db_index=True, max_length=150)),
                ('capacity', models.CharField(max_length=100)),
                ('verification_date', models.DateField()),
                ('expiry_date', models.DateField(db_index=True)),
                ('issuing_authority', models.CharField(default='Office of the Assistant Controller of Legal Metrology', max_length=255)),
                ('verifying_officer', models.CharField(max_length=255)),
                ('officer_designation', models.CharField(default='Senior Legal Metrology Officer', max_length=150)),
                ('seal_number', models.CharField(max_length=100)),
                ('fee_paid', models.CharField(max_length=50)),
                ('security_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_certificate', to='api.verificationapplication')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationTimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('actor', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='api.verificationapplication')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='verification_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.verificationapplication')),
            ],
        ),
    ]
